// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaUK_s60RrMedPxE0rpr0RLWoYMogXF7Q',
    appId: '1:353276133385:web:146cadf0c034fbffa738d8',
    messagingSenderId: '353276133385',
    projectId: 'talking-97cc3',
    authDomain: 'talking-97cc3.firebaseapp.com',
    storageBucket: 'talking-97cc3.firebasestorage.app',
    measurementId: 'G-GJMV1H11FH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAjW3WBBtXTgo4zjifZMEo5D5VHJRx4yc',
    appId: '1:353276133385:android:1511ea8a6252c729a738d8',
    messagingSenderId: '353276133385',
    projectId: 'talking-97cc3',
    storageBucket: 'talking-97cc3.firebasestorage.app',
  );
}
