name: saints_of_silence
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.7
  flutter_bloc: ^8.1.4
  cloud_firestore: ^4.17.5
  shared_preferences: ^2.5.3
  equatable: ^2.0.5
  
  flutter_launcher_icons: ^0.14.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon/appIcon_V5.png"  # Updated path for app icon
  adaptive_icon_background: "#ffffff"
  
flutter:
  uses-material-design: true
  
  assets:
    - assets/backgrounds/
    - assets/icons/
