name: bird_or_forest
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  http: ^1.2.2
  mime: ^1.0.4
  http_parser: ^4.0.2
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/appIcon.jpeg"  
  adaptive_icon_background: "#ffffff"
  windows:
    generate: true
    image_path: "assets/icons/appIcon.jpeg"  
    icon_size: 256   


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
