// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR2GesO38rFiCsqUI4273UQJsl57JMlRo',
    appId: '1:1068342579969:web:7f65c69813c3ef63410100',
    messagingSenderId: '1068342579969',
    projectId: 'saints-of-silence',
    authDomain: 'saints-of-silence.firebaseapp.com',
    storageBucket: 'saints-of-silence.firebasestorage.app',
    measurementId: 'G-JMGWGKMWH7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0ckFYOfKNtPuL1u_m7sD-qE90EDaRtps',
    appId: '1:1068342579969:android:0d58331a04279e76410100',
    messagingSenderId: '1068342579969',
    projectId: 'saints-of-silence',
    storageBucket: 'saints-of-silence.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBR2GesO38rFiCsqUI4273UQJsl57JMlRo',
    appId: '1:1068342579969:web:676069df715f4622410100',
    messagingSenderId: '1068342579969',
    projectId: 'saints-of-silence',
    authDomain: 'saints-of-silence.firebaseapp.com',
    storageBucket: 'saints-of-silence.firebasestorage.app',
    measurementId: 'G-KXE6C3ERH1',
  );
}
